apiVersion: v2
appVersion: v1.11.25
description: Communicate the way you want with Riot - a universal secure chat app entirely under your control.
icon: https://raw.githubusercontent.com/vector-im/element-web/develop/res/themes/element/img/logos/element-logo.svg
name: element-web
version: 1.4.0
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
  - element
home: https://element.io/
sources:
  - https://github.com/vector-im/element-web
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "**deps:** update vectorim/element-web docker tag to v1.11.30 ([c497bbd](https://github.com/halkeye-helm-charts/element-web/commit/c497bbd1f08047abe4cdf81b4960148bc874630a))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: element-web
      image: "vectorim/element-web:v1.11.30"
