apiVersion: v2
appVersion: "v1.7.24"
description: Communicate the way you want with Riot - a universal secure chat app entirely under your control.
icon: https://raw.githubusercontent.com/vector-im/element-web/develop/res/themes/element/img/logos/element-logo.svg
name: element-web
version: 1.0.8
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
  - element
home: https://element.io/
sources:
  - https://github.com/vector-im/element-web
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Make sure config.json.gz is generated
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: element-web
      image: vectorim/element-web:1.7.24
