{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "element-io.serviceAccountName" . }}
  labels:
{{ include "element-io.labels" . | indent 4 }}
{{- end -}}
